# -*- coding: utf-8 -*-
"""sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GqgO20YUf8gstJfHYS_KNq-WC2QUTWdl
"""

import pandas as pd

# 1. Load the dataset
# Using pandas to read the uploaded CSV file
df = pd.read_csv('sales_data.csv')

# 2. Check for and handle missing values appropriately
# First, we check if there are any missing values in the entire dataframe
missing_values_count = df.isnull().sum().sum()

if missing_values_count > 0:
    # Fill missing numeric values with 0 (assuming missing means no sales/qty)
    numeric_cols = df.select_dtypes(include=['number']).columns
    df[numeric_cols] = df[numeric_cols].fillna(0)

    # Fill missing categorical values with 'Unknown'
    cat_cols = df.select_dtypes(include=['object']).columns
    df[cat_cols] = df[cat_cols].fillna('Unknown')

# 3. Calculate key business metrics
# Metric 1: Total Sales (Sum of all revenue)
total_sales = df['Total_Sales'].sum()

# Metric 2: Best-Selling Product (Group by product and find the one with the max quantity sold)
product_quantities = df.groupby('Product')['Quantity'].sum()
best_selling_product = product_quantities.idxmax()
best_selling_qty = product_quantities.max()

# Metric 3: Highest Revenue Product (Group by product and find the max revenue)
top_revenue_product = df.groupby('Product')['Total_Sales'].sum().idxmax()

# Metric 4: Average Transaction Value (Mean of total sales per order)
avg_transaction_value = df['Total_Sales'].mean()

# Metric 5: Total Number of Orders
total_orders = len(df)

# 4. Create a clean, formatted report
report = f"""
======================================
         SALES DATA REPORT
======================================
Data Quality:
- Handled {missing_values_count} missing values.

Key Metrics:
1. Total Sales Revenue:        ${total_sales:,.2f}
2. Total Transactions:         {total_orders:,}
3. Average Transaction Value:  ${avg_transaction_value:,.2f}

Product Performance:
- Best-Selling Product (Qty):  {best_selling_product} ({best_selling_qty:,} units)
- Highest Revenue Product:     {top_revenue_product}
======================================
"""

# Output the report
print(report)